# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 16:20
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=20, null=True)),
                ('a_title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('a_info', models.CharField(max_length=200, verbose_name='文章描述')),
                ('a_author', models.CharField(max_length=50, verbose_name='文章作者')),
                ('a_img_url', models.CharField(max_length=255)),
                ('a_img_url_figer', models.CharField(max_length=255)),
                ('a_content_ue', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='文章内容')),
                ('a_createtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='添加时间')),
                ('a_price', models.IntegerField(default=0, null=True, verbose_name='单价')),
                ('a_flag', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, null=True, verbose_name='控制字段')),
                ('hot', models.IntegerField(default=0, null=True, verbose_name='热度')),
                ('operator', models.ForeignKey(db_column='operator', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='api操作者')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
                'db_table': 'art',
                'ordering': ['-a_createtime'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='章节标题')),
                ('content', models.TextField(null=True, verbose_name='小说章节内容')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='添加时间')),
                ('a_id', models.ForeignKey(db_column='a_id', on_delete=django.db.models.deletion.CASCADE, to='book.Art', verbose_name='小说')),
            ],
            options={
                'verbose_name': '小说章节',
                'verbose_name_plural': '小说章节',
                'db_table': 'art_chapter',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('a_content', models.TextField(null=True, verbose_name='小说内容')),
                ('a_id', models.ForeignKey(db_column='a_id', on_delete=django.db.models.deletion.CASCADE, to='book.Art', verbose_name='小说')),
            ],
            options={
                'verbose_name': '小说内容',
                'verbose_name_plural': '小说内容',
                'db_table': 'art_content',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=20, verbose_name='文章标签')),
                ('t_url', models.CharField(max_length=255, verbose_name='标签链接')),
                ('t_createtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('t_flag', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='控制字段')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tag',
                'ordering': ['-t_createtime'],
            },
        ),
        migrations.AddField(
            model_name='art',
            name='t_id',
            field=models.ForeignKey(db_column='t_id', on_delete=django.db.models.deletion.CASCADE, to='book.Tag', verbose_name='关联文章标签'),
        ),
    ]
